# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies separately (for caching)
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose development port
EXPOSE 3000

# Start Next.js in development mode
CMD ["npm", "run", "dev"]
